# Generated by Django 4.2.8 on 2024-01-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=62)),
                ('date', models.DateField()),
                ('unixStartTime', models.FloatField()),
                ('unixEndTime', models.FloatField()),
                ('accessCode', models.IntegerField()),
            ],
        ),
    ]
