# Generated by Django 4.2.8 on 2024-01-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserves',
            name='unixEndTime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserves',
            name='unixStartTime',
            field=models.IntegerField(),
        ),
    ]
